#!/usr/bin/env bash
# There can only be one

sudo touch /var/run/holbertonscript.pid
echo $$ >> sudo /var/run/holbertonscript.pid

sig_term()
{
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit 1
}

sig_quit()
{
    sudo rm /var/run/holbertonscript.pid
    exit 1
}

while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
	trap "sig_term" SIGTERM
	trap "sig_quit" SIGQUIT
	trap "echo 'Y U no love me?!'" SIGINT
done
