#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
HOURS=0
while (( HOURS <= 12 ))
do
echo "Hour: $HOURS"
	MINUTES=1
	while (( MINUTES <= 59))
	do
	echo "$MINUTES"
	(( MINUTES += 1 ))
	done
(( HOURS += 1 ))
done
