#!/usr/bin/env bash
# gives information about the holbertonschool file
HFILE=holbertonschool
if [ -e $HFILE ]
then
	echo "holbertonschool file exists"
	if [ -s $HFILE ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $HFILE ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
