#!/usr/bin/env bash
# Install nginx web server
# Replace default page with Holberton School
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
service nginx start
