#!/usr/bin/env bash
# Sets up custom 404 page
FILE=/etc/nginx/sites-available/default
REDIRECT="location /redirect_me {\n return 301 https://youtu.be/dQw4w9WgXcQ;\n}\n"
STRING=" error_page 404 /custom_404.html;\n location = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
service nginx start
sudo sed -i "30i $REDIRECT" $FILE
sudo sed -i "33i$STRING" $FILE
service nginx restart
